insert into gerecht (id, naam, prijs, categorie) values (1, 'steak tartaar met tuffelmayonaisse', 7.50, 0)
insert into gerecht (id, naam, prijs, categorie) values (2, 'Paté van fazant met monegaskische uitjes', 8.50, 0)
insert into gerecht (id, naam, prijs, categorie) values (3, 'Provencaalse vissoep met rouille, oude kaas en croutons', 6.50, 0)
insert into gerecht (id, naam, prijs, categorie) values (4, 'Hertenstoofpotje met rode kool',12.50, 1)
insert into gerecht (id, naam, prijs, categorie) values (5, 'Gebakken kabeljauw met curry-sabayon', 14.50, 1)
insert into gerecht (id, naam, prijs, categorie) values (6, 'Liguini met paddenstoelen saus', 13.50, 1)
insert into gerecht (id, naam, prijs, categorie) values (7, 'Taart van witte chocolade en speculaas met mandarijn', 5.50, 2)
insert into gerecht (id, naam, prijs, categorie) values (8, 'Verse madeleines met vijgen compote en creme patissiermet grand manier', 6.50, 2)
insert into gerecht (id, naam, prijs, categorie) values (9, '3 soorten boerenkazen met rogge rozijnenbrood', 5, 2)
insert into gerecht (id, naam, prijs, categorie) values (10, 'Kalfstartaar met tonijnmayonaise en gefrituurde mosselen', 8.50, 0)
insert into gerecht (id, naam, prijs, categorie) values (11, 'Paté van fazant met Monegaskische uitjes', 8.50, 0)
insert into gerecht (id, naam, prijs, categorie) values (12, 'Krab-zalm koekjes met zoetzure-chilisaus',9.00, 0)
insert into gerecht (id, naam, prijs, categorie) values (13, 'Provençaalse vissoep met rouille en croutons',6.50, 3)
insert into gerecht (id, naam, prijs, categorie) values (14, 'Consommé van fazant met bosui en groene kruiden', 7.50, 3)
insert into gerecht (id, naam, prijs, categorie) values (15, 'Op de huid gebakken kabeljauw rug filet met curry-sabayon',17.50,1)
insert into gerecht (id, naam, prijs, categorie) values (16, 'Gebakken ossenhaas met kalf-jus met roze pepers', 22.50,1)
insert into gerecht (id, naam, prijs, categorie) values (17, 'Hertenbiefstuk met eigen stoof en rode kool', 25.00,1)
insert into gerecht (id, naam, prijs, categorie) values (18, 'Café surprise (Koffie met huisgemaakte bonbons)', 5.50, 2)
insert into gerecht (id, naam, prijs, categorie) values (19, 'Cherry Baby ( Slagroomijs met warme kersen)', 6.50, 2)
insert into gerecht (id, naam, prijs, categorie) values (20, 'Port e Fromage (verschillende kazen met glaasje port)',7.50, 2)
insert into gerecht (id, naam, prijs, categorie) values (21, 'Spa rood', 2.5, 4)
insert into gerecht (id, naam, prijs, categorie) values (22, 'Spa groen', 2.50, 4)
insert into gerecht (id, naam, prijs, categorie) values (23, 'Coca Cola Light', 2.5, 4)
insert into gerecht (id, naam, prijs, categorie) values (24, 'Coca Cola', 2.5, 4)
insert into gerecht (id, naam, prijs, categorie) values (25, 'Sisi', 2.5,4)
insert into gerecht (id, naam, prijs, categorie) values (26, 'Tonic', 2.5,4)
insert into gerecht (id, naam, prijs, categorie) values (27, 'Bitter Lemon', 2.5, 4)
insert into gerecht (id, naam, prijs, categorie) values (28, 'Hertog jan', 3,5)
insert into gerecht (id, naam, prijs, categorie) values (29, 'Duvel', 4.5,5)
insert into gerecht (id, naam, prijs, categorie) values (30, 'Kriek', 4, 5)
insert into gerecht (id, naam, prijs, categorie) values (31, 'Leffe Triple', 4.5,5)
insert into gerecht (id, naam, prijs, categorie) values (32, 'Witte Huiswijn fles', 28.50, 6)
insert into gerecht (id, naam, prijs, categorie) values (33, 'Witte Huiswijn glas', 6.50, 6)
insert into gerecht (id, naam, prijs, categorie) values (34, 'Rode Huiswijn fles', 32,6)
insert into gerecht (id, naam, prijs, categorie) values (35, 'Rode Huiswijn glas', 7.50,6)
insert into gerecht (id, naam, prijs, categorie) values (36, 'Champagne fles',50,6)
insert into gerecht (id, naam, prijs, categorie) values (37, 'Jonge Jenever' 3.5, 7)
insert into gerecht (id, naam, prijs, categorie) values (38, 'Whiskey', 5, 7)
insert into gerecht (id, naam, prijs, categorie) values (39, 'Rum', 4.5, 7)
insert into gerecht (id, naam, prijs, categorie) values (40, 'Viex', 4.5, 7)
insert into gerecht (id, naam, prijs, categorie) values (41, 'Berenbrug', 3.5, 7)
insert into gerecht (id, naam, prijs, categorie) values (42, 'Koffie', 2.5, 8)
insert into gerecht (id, naam, prijs, categorie) values (43, 'Cappuchino', 3.5, 8)
insert into gerecht (id, naam, prijs, categorie) values (44, 'Expresso', 3, 8)
insert into gerecht (id, naam, prijs, categorie) values (45, 'Thee', 2.5, 8)